### ISSUE TITLE
Notification page: Neither the property "entry" nor one of the methods "entry()" in dev mode

### ISSUE THREAD

**Issue by melroy89** [MbinOrg/mbin#1071]
**Describe the bug**

Frontend crash in Twig template at the notification page.

**On which Mbin instance did you find the bug?**
kbin.melroy.org

**Which Mbin version was running on the instance?**
1.7.1

**To Reproduce**
1. Run in dev mode
2. Go to Notifications

Error message:

```sh
[2024-08-31T14:15:29.877481+02:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "entry" nor one of the methods "entry()", "getentry()"/"isentry()"/"hasentry()" or "__call()" exist and have public access in class "App\Entity\EntryCommentReport"." at _blocks.html.twig line 104 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"entry\" nor one of the methods \"entry()\", \"getentry()\"/\"isentry()\"/\"hasentry()\" or \"__call()\" exist and have public access in class \"App\\Entity\\EntryCommentReport\". at /var/www/kbin.melroy.org/html/templates/notifications/_blocks.html.twig:104)
[stacktrace]
#0 /var/www/kbin.melroy.org/html/var/cache/dev/twig/80/808539e6f82f6bfc653a06193bce03f6.php(873): Twig\\Extension\\CoreExtension::getAttribute()
#1 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Template.php(430): __TwigTemplate_788c432cb478dc9a06bcf5acf7ea54d7->block_reportlink()
#2 /var/www/kbin.melroy.org/html/var/cache/dev/twig/80/808539e6f82f6bfc653a06193bce03f6.php(966): Twig\\Template->yieldBlock()
#3 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Template.php(430): __TwigTemplate_788c432cb478dc9a06bcf5acf7ea54d7->block_report_created_notification()
#4 /var/www/kbin.melroy.org/html/var/cache/dev/twig/b0/b0f71fe94567e6b7e0f3673bbd68ed95.php(268): Twig\\Template->yieldBlock()
#5 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Template.php(430): __TwigTemplate_1043b0e468c799d438c19fd907c5fc8a->block_body()
#6 /var/www/kbin.melroy.org/html/var/cache/dev/twig/da/da33571efdb9963c057e42bf4f3eef11.php(225): Twig\\Template->yieldBlock()
#7 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Template.php(360): __TwigTemplate_80e96a77400a074f388e2f2541f03620->doDisplay()
#8 /var/www/kbin.melroy.org/html/var/cache/dev/twig/b0/b0f71fe94567e6b7e0f3673bbd68ed95.php(65): Twig\\Template->yield()
#9 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Template.php(360): __TwigTemplate_1043b0e468c799d438c19fd907c5fc8a->doDisplay()
#10 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Template.php(335): Twig\\Template->yield()
#11 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\\Template->render()
#12 /var/www/kbin.melroy.org/html/vendor/twig/twig/src/Environment.php(307): Twig\\TemplateWrapper->render()
#13 /var/www/kbin.melroy.org/html/vendor/symfony/framework-bundle/Controller/AbstractController.php(431): Twig\\Environment->render()
#14 /var/www/kbin.melroy.org/html/vendor/symfony/framework-bundle/Controller/AbstractController.php(436): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->doRenderView()
#15 /var/www/kbin.melroy.org/html/vendor/symfony/framework-bundle/Controller/AbstractController.php(250): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->doRender()
#16 /var/www/kbin.melroy.org/html/src/Controller/User/Profile/UserNotificationController.php(20): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->render()
#17 /var/www/kbin.melroy.org/html/vendor/symfony/http-kernel/HttpKernel.php(183): App\\Controller\\User\\Profile\\UserNotificationController->notifications()
#18 /var/www/kbin.melroy.org/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#19 /var/www/kbin.melroy.org/html/vendor/symfony/http-kernel/Kernel.php(182): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#20 /var/www/kbin.melroy.org/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\\Component\\HttpKernel\\Kernel->handle()
#21 /var/www/kbin.melroy.org/html/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner->run()
#22 /var/www/kbin.melroy.org/html/public/index.php(7): require_once('...')
#23 {main}
"} []
```

**Expected behavior**

No errors :).

**Screenshots**

![image](https://github.com/user-attachments/assets/340e8c97-1ce3-405b-8e5e-5a0217fe0964)

**Comment by BentiGorlich** [comment]
can you check whether some migration did not execute on your instance properly? Because I have no problem with the notification page on my dev instance

**Comment by melroy89** [comment]
Hm. I once did a manual migration. so I can ignore this warning?
`[WARNING] You have 1 previously executed migrations in the database that are not registered migrations. `

Anyway, there is indeed a diff in my case. After running: `./bin/console doctrine:migrations:diff`.

You don't have this?
```
        $this->addSql('ALTER TABLE entry ALTER title_ts SET DEFAULT \'english\'');
        $this->addSql('ALTER TABLE entry ALTER body_ts SET DEFAULT \'english\'');
        $this->addSql('ALTER TABLE entry_comment ALTER body_ts SET DEFAULT \'english\'');
        $this->addSql('ALTER TABLE post ALTER body_ts SET DEFAULT \'english\'');
        $this->addSql('ALTER TABLE post_comment ALTER body_ts SET DEFAULT \'english\'');
```

**Comment by melroy89** [comment]
I dumped the `notification.report` variable. I see:

```
[App\Entity\EntryCommentReport](file:///var/www/kbin.melroy.org/html/src/Entity/EntryCommentReport.php#L12) {#2783 ▼
  +magazine: [Proxies\__CG__\App\Entity\Magazine](file:///var/www/kbin.melroy.org/html/var/cache/dev/doctrine/orm/Proxies/__CG__AppEntityMagazine.php#L8) {#2842 ▶}
  +reporting: [Proxies\__CG__\App\Entity\User](file:///var/www/kbin.melroy.org/html/var/cache/dev/doctrine/orm/Proxies/__CG__AppEntityUser.php#L8) {[#2986 ▶](https://kbin.melroy.org/settings/notifications#sf-dump-265778249-ref22986)}
  +reported: [Proxies\__CG__\App\Entity\User](file:///var/www/kbin.melroy.org/html/var/cache/dev/doctrine/orm/Proxies/__CG__AppEntityUser.php#L8) {[#3080 ▶](https://kbin.melroy.org/settings/notifications#sf-dump-265778249-ref23080)}
  +consideredBy: [App\Entity\User](file:///var/www/kbin.melroy.org/html/src/Entity/User.php#L46) {[#95 ▶](https://kbin.melroy.org/settings/notifications#sf-dump-265778249-ref295)}
  +reason: "calls for violence"
  +weight: 1
  +status: "rejected"
  +uuid: "f9a6e8cd-15ea-4fe0-8630-0d15d13c92b7"
  -id: 91
  +createdAt: DateTimeImmutable @1725060985 {#2780 ▶}
  +consideredAt: DateTimeImmutable @1725113609 {#2749 ▶}
  +entryComment: [Proxies\__CG__\App\Entity\EntryComment](file:///var/www/kbin.melroy.org/html/var/cache/dev/doctrine/orm/Proxies/__CG__AppEntityEntryComment.php#L8) {#3083 ▶}
}
```

(this is a rejected report, without any entry)
